version: 2015.1.{build}
clone_depth: 1

install:
    - echo "Downloading deps..."
    - ps: (new-object System.Net.WebClient).Downloadfile("http://swdownloads.analog.com/cse/build/libiio-win-deps.zip", "c:\libiio-win-deps.zip")
    - 7z x -y "c:\libiio-win-deps.zip" -o"C:\" > nul
    - choco install InnoSetup
    - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"

build_script:
    - echo "Running cmake for Win32..."
    - mkdir c:\projects\libiio\build-win32
    - cd c:\projects\libiio\build-win32
    - set MCS_EXECUTABLE_PATH="C:\Windows\Microsoft.NET\Framework\v4.0.30319"
    - cmake -G "Visual Studio 12" -DENABLE_IPV6:BOOL=OFF -DLIBXML2_LIBRARIES="C:\\libs\\32\\libxml2.lib" -DLIBUSB_LIBRARIES="C:\\libs\\32\\libusb-1.0.lib" -DCMAKE_SYSTEM_PREFIX_PATH="C:" -DCMAKE_CONFIGURATION_TYPES=Release ..
    - msbuild /m /p:Configuration=Release /p:Platform="Win32" libiio.sln
    - echo "Running cmake for Win64..."
    - mkdir c:\projects\libiio\build-win64
    - cd c:\projects\libiio\build-win64
    - cmake -G "Visual Studio 12 Win64" -DENABLE_IPV6:BOOL=OFF -DCSHARP_BINDINGS:BOOL=OFF -DLIBXML2_LIBRARIES="C:\\libs\\64\\libxml2.lib" -DLIBUSB_LIBRARIES="C:\\libs\\64\\libusb-1.0.lib" -DCMAKE_SYSTEM_PREFIX_PATH="C:" -DCMAKE_CONFIGURATION_TYPES=Release ..
    - msbuild /m /p:Configuration=Release /p:Platform="x64" libiio.sln
    - ISCC C:\projects\libiio\build-win32\libiio.iss
    - appveyor PushArtifact C:\libiio-setup.exe

deploy:
    tag: $(appveyor_repo_tag_name)
    release: Libiio release 2015.1-$(appveyor_build_number)
    artifact: libiio-setup.exe
    provider: GitHub
    auth_token:
        secure: kN/6ER7Noz0gJB9Cb9jkWhn4lDwp+g3hFLeJsRmknhZihyCkqpqfghf//NZrtHbQ
    prerelease: true
    on:
        branch: 2015_R1
        appveyor_repo_tag: true
